name: Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  issues: write
  pull-requests: write
  contents: read

env:
  TF_LOG: INFO

jobs:
  pr-infra-check-nonprod:
    runs-on: ubuntu-latest
    environment: nonprod
    env:
      STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Az CLI login (Nonprod)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify subscription (Nonprod)
        run: az account show

      - name: Terraform Init (Nonprod)
        id: init-nonprod
        run: |
          terraform init \
            -backend-config="storage_account_name=${STORAGE_ACCOUNT}" \
            -backend-config="container_name=${CONTAINER_NAME}" \
            -backend-config="resource_group_name=${RESOURCE_GROUP_NAME}"

      - name: Terraform Validate (Nonprod)
        run: terraform validate -no-color

      - name: Terraform Plan (Nonprod)
        run: terraform plan -no-color -out=.planfile -input=false -var 'environment=nonprod'

      - name: Post Plan Comment (Nonprod)
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          planfile: .planfile
          header: "### Terraform Plan: nonprod"

  pr-infra-check-prod:
    runs-on: ubuntu-latest
    environment: prod
    env:
      STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Az CLI login (Prod)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify subscription (Prod)
        run: az account show

      - name: Terraform Init (Prod)
        id: init-prod
        run: |
          terraform init \
            -backend-config="storage_account_name=${STORAGE_ACCOUNT}" \
            -backend-config="container_name=${CONTAINER_NAME}" \
            -backend-config="resource_group_name=${RESOURCE_GROUP_NAME}"
            
      - name: Terraform Validate (Prod)
        run: terraform validate -no-color

      - name: Terraform Plan (Prod)
        run: terraform plan -no-color -out=.planfile -input=false -var 'environment=prod'

      - name: Post Plan Comment (Prod)
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          planfile: .planfile
          header: "### Terraform Plan: prod"
